version: "3"
services:
  backend:
    build:
      context: ./Backend/  
      dockerfile: Dockerfile
    container_name: backend-container-compose
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./FrontEnd/
      dockerfile: Dockerfile
    container_name: online-book-store-compose
    ports:
      - "5173:5173"
