version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo-container-compose
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./Backend/  
      dockerfile: Dockerfile
    container_name: backend-container-compose
    ports:
      - "8000:8000"
    links:
      - mongo

  frontend:
    build:
      context: ./FrontEnd/
      dockerfile: Dockerfile
    container_name: online-book-store-compose
    ports:
      - "5173:5173"

networks:
  my-network: